allIngredients = [
    "1 package blanched whole almonds",
    "1 1/2 lb thinly sliced bacon",
    "1 pound pitted dates",
    "8 cups of apples, peeled and seeded",
    "1 cup of fresh cider",
    "1/3 cup brown sugar",
    "2 cups flour",
    "1 teaspoon salt",
    "1 teaspoon baking soda",
    "1/4 teaspoon cloves",
    "1/4 teaspoon nutmeg",
    "1 teaspoon cinnamon",
    "1 cup dates  (quartered)",
    "1 cup seedless raisins",
    "1/2 cup margarine",
    "1 cup sugar",
    "1 egg substitute",
    "1 cup apple butter",
    "1/3 cup lightly packed brown sugar",
    "1/3 cup oats",
    "3 tablespoons wholemeal flour",
    "2 tablespoons margarine  (melted)",
    "2/3 cup granulated white sugar",
    "3 tablespoons flour",
    "2 cups sliced apples",
    "2 cups diced rhubarb",
    "1 cup cranberries fresh or frozen",
    "5 - 6 cups sliced apple",
    "3/4 cup sugar",
    "1 cup flour",
    "1 tsp baking powder",
    "3/4 tsp salt",
    "1 egg",
    "1/3 cup solid shortening (e.g. Crisco)",
    "1/2 tsp cinnamon",
    "1 kg cooking apples, peeled, thinly sliced",
    "1/2 C sultanas",
    "1/2 C brown sugar",
    "1/4 tsp cinnamon",
    "1 1/2 C self-raising flour",
    "pinch of salt",
    "80g Butter",
    "1/2 brown sugar",
    "1 1/2 tsp mixed spices",
    "1 cup water",
    "1/2 cup apple juice",
    "pinch salt",
    "2/3 cup of granola",
    "1 large McIntosh apple, diced",
    "8 cups peeled tart apples  (sliced)",
    "2 cups dates  (chopped)",
    "2/3 cup packed brown sugar",
    "1/2 cup flour",
    "1 teaspoon cinnamon",
    "1/3 cup butter",
    "1 cup chopped nuts",
    "2 1/4 cups wholemeal flour",
    "1 1/2 teaspoons baking soda",
    "1/3 cup brown sugar, packed",
    "3/4 cup buttermilk, nonfat",
    "1 1/2 cups apples, finely chopped",
    "2 eggs",
    "1 teaspoon vanilla",
    "1/2 cup chopped dates",
    "6 medium apples, cored and sliced",
    "1 cup raisins",
    "1/4 granulated sugar",
    "1 Tbsp flour",
    "1/4 cup packed brown sugar",
    "1 unbaked prepared pir crust",
    "1/2 tsp cinnamon",
    "1 large egg 1 tsp sugar 1/4 tsp nutmeg",
    "6 - 8 Apples",
    "3/4 cup water",
    "1/3 - 1/2 cup sugar (or to taste)",
    "1/2 tsp cinnamon",
    "1/4 tsp nutmeg (optional)",
    "2 cups flour",
    "1 cup wholemeal flour",
    "2 teaspoons baking powder",
    "2 teaspoons cinnamon",
    "1/2 teaspoon baking soda",
    "1/2 teaspoon salt",
    "2 eggs",
    "1 1/3 cups brown sugar  (packed)",
    "1 1/3 cups applesauce",
    "1/2 cup oil",
    "1 1/2 cups rhubarb  (chopped)",
    "3 cups sliced fresh or frozen rhubarb",
    "1/3 cup sugar",
    "1/4 cup orange juice",
    "1 pint fresh strawberries  (halved)",
    "fresh mint (optional)",
    "1 head of brocolli",
    "1/2 red onion",
    "Juice from one lemon",
    "1 rasher of bacon cut finely",
    "35g Almond slivers",
    "1 teaspoon of mayonnaise",
    "1 Tablespoon of yogurt",
    "1 cup dates  (shredded)",
    "3/4 teaspoon baking soda",
    "1 cup boiling water",
    "1 egg  (beaten)",
    "1/2 cup maple syrup",
    "1 teaspoon salt",
    "1 cup flour",
    "1 cup wholemeal flour",
    "1 teaspoon baking powder",
    "1/2 cup nuts  (chopped)",
    "1 C Self-Raising Flour",
    "3/4 C Sugar",
    "Pinch of Salt",
    "60 g Butter",
    "1 1/2 C Milk",
    "1 packet cannelloni tubes (about 16)",
    "2 medium-Sized onions",
    "4 cloves garlic",
    "2 Tbsp oil",
    "1 small green pepper",
    "1 tsp basil",
    "1/2 tsp thyme",
    "1/2 tsp sugar",
    "1/2 tsp salt",
    "1 300 g can tomato puree",
    "1 Tbsp wine vinegar",
    "1/4 cup water",
    "1 kg of fresh spinach (2 cups when lightly cooked)",
    "1 cup cottage cheese",
    "1 tsp dried oreganum",
    "1/2 tsp salt",
    "1/2 tsp sugar",
    "1/4 tsp grated nutmeg",
    "black pepper to taste",
    "1 cup cream cheese",
    "1 cup grated cheese",
    "2 eggs",
    "1 cup brown sugar",
    "180 g butter, melted",
    "1/2 cup milk",
    "2 tablespoons coffee and chicory essence",
    "1 C dates, pitted and chopped into small pieces",
    "1 1/2 C flour",
    "2 C icing sugar",
    "1 tablespoons coffee and chicory essence",
    "25g butter, melted",
    "boiling water",
    "1 C Bran",
    "1/2 C Wheatgerm",
    "1 C Flour",
    "1 tsp Soda",
    "1 tsp Baking Powder",
    "2 tsp Mixed Spice",
    "3 eggs",
    "3/4 C sugar",
    "1/2 C oil",
    "2 1/2 C carrot",
    "1 C raisins",
    "1/2 C walnuts",
    "8 oz Dates  (Finely) Chopped",
    "2 tbsp Butter",
    "3/4 c Water (Boiling)",
    "1 3/4 c flour (Sifted)",
    "1/4 tsp Salt",
    "1 tsp Baking Soda",
    "1/2 c Sugar  (Granulated)",
    "1 large egg",
    "4 oz Cheddar, Shredded",
    "1 c Walnuts  (Chopped)",
    "3/4 cup flour",
    "3 tablespoons sugar",
    "1 teaspoon lemon peel  (grated)",
    "6 tablespoons butter",
    "1 egg yolk  (slighly) beaten",
    "1/2 teaspoon vanilla",
    "24 ounces cream cheese  (softened)",
    "1 cup sugar",
    "2 tablespoons flour",
    "1/4 teaspoon salt",
    "2 eggs",
    "1 egg yolk",
    "1/4 cup milk",
    "3/4 cup sugar",
    "2 tablespoons cornstarch",
    "1 dash salt",
    "1/3 cup water",
    "4 cups cherries",
    "3 1/3 c flour",
    "1 tbsp Baking Powder",
    "1 tsp Baking Powder",
    "1 tsp Salt",
    "1/4 c Sugar",
    "1 large Egg, Beaten",
    "2/3 c Tart Cherries, Well Drained",
    "2 tsp almond essence",
    "1 3/4 c Milk",
    "1/3 c Vegetable Oil",
    "1/3 c Nuts, Chopped (Optional)",
    "125g butter",
    "3/4 C sugar",
    "2 Tbsp golden syrup",
    "2 large eggs",
    "1 tsp vanilla",
    "2 cups flour",
    "1/2 tsp baking soda",
    "2 tsp baking powder",
    "1/2 cup milk",
    "2 Tbsp cocoa",
    "1 Tbsp milk",
    "250 g Butter",
    "1/2 C Sugar",
    "1/2 Tin Condensed milk",
    "3 C Flour",
    "2 tsp Baking Powder",
    "1/2 C Chocolate Chips",
    "2 cups self-raising four",
    "1/2 cup castor sugar",
    "1/2 cup chocolate chips",
    "1/2 tsp salt",
    "100g butter",
    "1 cup milk",
    "1 large egg",
    "1 tsp vanilla",
    "1 cup (2-3) mashed bananas",
    "3/4 cup butter",
    "1 1/2 cups flour",
    "1 cup brown sugar, packed",
    "3/4 cup confectioners sugar",
    "2 eggs",
    "1/2 tsp salt",
    "2 Tbs. flour",
    "1/2 tsp baking powder",
    "1/2 tsp vanilla",
    "1/2 cup chopped walnuts",
    "1/2 cup flaked coconut",
    "2 c Sugar",
    "1 tbsp Light corn syrup",
    "3/4 c Evaporated milk",
    "6 3/4 oz Pitted dates",
    "2 tbsp Butter",
    "1 c Chopped nuts",
    "1/2 tsp vanilla",
    "1/8 tsp Salt",
    "1 1/2 c Flaked coconut, toasted",
    "1 package shredded coconut",
    "1 lb. confectioners sugar",
    "1 1/2 cups peanut butter (crunchy or smooth)",
    "1 box bakers chocolate (semi sweet)",
    "1/8 lb. parafin",
    "16 oz whole cranberry sauce",
    "1/3 cup granulated sugar",
    "1 1/2 tablespoons cornstarch",
    "3/4 pound rhubarb stalks, cut into 1/2- inch pieces",
    "pastry dough for 9-inch single crust pie",
    "confectioner's sugar",
    "1/2 cup dates  (dried),finely chopped",
    "1 egg",
    "1 cup sugar",
    "2 tablespoons butter  (melted)",
    "2 cups flour  (all)-purpose,sifted",
    "3 teaspoons baking powder",
    "1/4 teaspoon baking soda",
    "3/4 teaspoon salt",
    "1/2 cup orange juice",
    "1/4 cup water",
    "1 cup pecans  (chopped)",
    "1/2 C Boiling water",
    "1/2 C Cocoa",
    "170 g Butter",
    "1 1/2 C Castor Sugar",
    "3 Eggs, beaten",
    "1 tsp Vanilla",
    "2 C Self-raising Flour",
    "Pinch of Salt",
    "1/4 tsp Baking Soda",
    "3/4 C Milk",
    "1/2 cup butter",
    "1 cup sugar",
    "2 eggs",
    "1 tsp lemon rind, grated",
    "1/8 tsp lemon extract",
    "1 1/2 cups flour",
    "1 1/2 tsp baking powder",
    "1/8 tsp salt",
    "1/2 cup milk",
    "1/2 cup sugar juice of 1 lemon",
    "1 package yellow cake mix",
    "1/2 cup vegetable oil",
    "1 package instant lemon pudding",
    "3 eggs",
    "1 cup orange juice",
    "1 1/2 cups confectioners sugar",
    "2 Tbs. butter",
    "1/3 cup lemon juice",
    "rind of 2 lemons",
    "1 cup oil",
    "2 eggs",
    "1 3/4 cups sugar",
    "1/2 tsp salt",
    "1 cup greek yoghurt",
    "3 Tbsp lemon juice",
    "2 cups self-raising flour",
    "3 C Flour",
    "2 C Sugar",
    "2 tsp Baking Soda",
    "2 tsp Baking Powder",
    "1 tsp Cinnamon",
    "1/2 tsp Salt",
    "4 eggs",
    "1 1/2 C Vegetable Oil",
    "1 tsp vanilla",
    "3 C Banana",
    "1 C Walnuts",
    "1 C Crushed Pineapple (Drained)",
    "30 g butter",
    "1/2 onion, finely chopped",
    "2 cups fresh bread crumbs",
    "1 diced apple, peeled",
    "2 rashers bacon (optional)",
    "1/2 cup chopped fresh herbs (parsley, sage, thyme, dill, rosemary, chives, oregano)*",
    "salt and freshly ground black pepper to taste",
    "1/2 cup sultanas, apricots or chopped prunes",
    "1/2 onion, finely chopped",
    "30g butter",
    "2 cups breadcrumbs",
    "1 apple",
    "salt and pepper",
    "1/2 cup sultanas",
    "2 rashers of bacon",
    "1/2 cup chopped parsley, sage, thyme, rosemary",
    "1 1/4 teaspoons yeast  (dry)",
    "1 3/4 cups bread flour",
    "1/2 cup wholemeal flour",
    "2 teaspoons cinnamon",
    "2 teaspoons ground ginger",
    "1/2 teaspoon ground cloves",
    "1/2 teaspoon salt",
    "1/4 cup banana  (mashed) ripe",
    "4 dates  (minced)",
    "3/4 cup water",
    "8 apple",
    "1/2 cup apple juice  (concentrate)",
    "1/2 teaspoon cinnamon",
    "1 orange (about 200g)",
    "1 cup sugar",
    "1 large egg",
    "200g yoghurt",
    "100g butter, melted",
    "1 1/2 cups standard (plain) flour",
    "1 tsp baking powder",
    "1 tsp baking soda",
    "1/2 cup sultanas",
    "1/2 cup chopped walnuts (optional)",
    "4 Egg Whites",
    "1 1/4 C Sugar",
    "1 tsp Vinegar",
    "1 tsp Vanilla",
    "Pinch of Cream of Tartar",
    "1 Tbsp Cornflour",
    "Pinch of Salt",
    "1 15oz. package frozen raspberries",
    "1 1/2 tsp cornstarch",
    "6 - 12 peach halves",
    "Vanilla icecream",
    "6 - 8 large cooked potatoes, diced",
    "1 cup cooked drained spinach",
    "150g feta, crumbled",
    "2 tomatoes, thinly sliced",
    "12 large eggs",
    "1 tsp salt, pepper",
    "1/2 cup chopped fresh herbs, eg",
    "parsley",
    "basil",
    "100g gruyere, grated",
    "900 g potatoes, peeled and sliced",
    "salt and pepper",
    "1 - 2 garlic cloves, skinned and crushed",
    "pinch of nutmeg, freshly grated",
    "150 ml cream",
    "75 g gruyere cheese, grated",
    "1 16 oz. package pound cake mix",
    "3 eggs",
    "2 Tbs. butter, melted",
    "4 tsp pumpkin pie spice",
    "1 8oz. package cream cheese",
    "1 14oz. can sweetened condensed milk",
    "1 16oz. can pumpkin",
    "1/2 tsp salt",
    "1 cup chopped nuts",
    "4 eggs, beaten",
    "2 cups sugar",
    "1 1/2 cups oil",
    "1 14 oz. can pumpkin",
    "3 cups flour",
    "2 1/2 tsp cinnamon",
    "1 tsp nutmeg",
    "2 tsp baking soda",
    "2 tsp baking powder",
    "1 tsp salt",
    "2 cups raisins",
    "2 Tbsp Olive Oil",
    "2 Tbsp Butter",
    "1 Onion, chopped",
    "1 Tbsp Curry Powder",
    "2 Tbsp Tomato Paste",
    "1 kg Pumpkin, Diced",
    "6 C Chicken Stock",
    "Juice of 1 Lemon",
    "1/2 C Cream",
    "salt and pepper",
    "2 onions, chopped",
    "2 garlic cloves",
    "1 Tbsp oil",
    "1 green capsicum (optional)",
    "1 red capsicum (optional)",
    "1/2 tsp chilli powder",
    "2 tsp ground cumin",
    "1 tsp oreganum, crumbled",
    "1 - 2 cooked carrots (optional)",
    "1/2 tsp salt",
    "1/2 tsp sugar",
    "425 g can kidney beans",
    "1 rounded Tbsp tomato paste",
    "3/4 cup Brown sugar",
    "3/4 cup White sugar",
    "1 Egg",
    "3/4 cup Shortening",
    "2 cups Flour",
    "1 Dash salt",
    "1 teaspoon Vanilla",
    "1 teaspoon Cinnamon",
    "1 cup Milk",
    "1 teaspoon Vinegar",
    "1 teaspoon Baking soda",
    "1 1/2 cups Rhubarb; uncooked  (sliced)",
    "1 cup Brown sugar",
    "1 teaspoon Cinnamon",
    "1/2 cup Nuts  (chopped)",
    "2 cups sugar",
    "3 tablespoons flour",
    "2 eggs  (beaten)",
    "5 1/2 cups coarsely chopped rhubarb",
    "2 8\" unbaked pie shells",
    "1 cup flour",
    "1/2 cup brown sugar",
    "1/4 cup shortening",
    "1/2 teaspoon baking soda",
    "1/2 teaspoon baking powder",
    "2 cups flour",
    "1 cup wholemeal flour",
    "2 teaspoons baking powder",
    "2 teaspoons cinnamon",
    "1/2 teaspoon baking soda",
    "1/2 teaspoon salt",
    "2 eggs",
    "1 1/3 cups brown sugar  (packed)",
    "1 1/3 cups applesauce",
    "1/2 cup oil",
    "1 1/2 cups rhubarb  (chopped)",
    "4 c uncooked risoni",
    "Garlic",
    "8 rashers of bacon",
    "4 chicken breasts",
    "12 Mushrooms",
    "1 - 2 packs of baby spinach",
    "1 300g block of feta chopped into cm cubes",
    "1/3 cup lemon juice",
    "1/3 cup olive oil",
    "Mustard",
    "Pesto",
    "1/3 C Sweet chilli sauce",
    "salt and pepper",
    "3 C Flour",
    "6 tsp Baking Powder",
    "1/4 Salt",
    "75 g Butter",
    "1 1/2 C Milk",
    "4 teaspoons active dry yeast",
    "1 teaspoon white sugar",
    "1 1/4 cups warm water (110 degrees F/45 degrees C)",
    "5 cups flour",
    "1/2 cup white sugar",
    "1 1/2 teaspoons salt",
    "1 tablespoon vegetable oil",
    "1/2 cup baking soda",
    "4 cups hot water",
    "1/4 cup sea salt",
    "1 8 oz cream cheese  (softened)",
    "1/3 cup sugar",
    "1/2 tsp almond essence",
    "1 cup whipped cream",
    "4 cups strawberries",
    "1/2 cup chocolate chips  (semi)-sweet",
    "1 tablespoon shortening",
    "10 pastry shells",
    "1 cup double-thick yogurt",
    "1/4 cup firmly packed brown sugar",
    "1/2 teaspoon cinnamon",
    "1 teaspoon vanilla",
    "2 tablespoons strawberry liqueur -- (optional)",
    "2 pints fresh strawberries  (about) 24 oz.,washed",
    "2 Tablespoons pecan pieces  (lightly) toasted",
    "2 c strawberries  (halves)",
    "1/4 c nonfat sour cream",
    "1/4 tsp cinnamon  (ground)",
    "1/4 c brown sugar  (packed)",
    "Ice cream",
    "3 pints Strawberries, hulled and halved",
    "1/2 cup Sugar",
    "2 tablespoons Fresh lemon juice",
    "1/4 cup Dried apricots",
    "1/4 cup water",
    "1/3 cup Sugar",
    "2 large Egg whites",
    "1/8 cup Shredded unsweetened, toasted coconut",
    "1 1/2 pounds Cream cheese, room temp.",
    "1 1/4 cups Sugar",
    "1/4 teaspoon Salt",
    "3/4 cup Sour cream",
    "1 tablespoon Dark rum",
    "1 tablespoon Fresh lemon juice",
    "2 teaspoons vanilla",
    "3 large Eggs",
    "1 1/2 pints Strawberries; hulled, halved, stems intact",
    "Fresh mint sprigs (optional)",
    "3 pints fresh strawberries  (sliced)",
    "1 1/2 cups heavy cream  (whipped)",
    "3/4 cup very soft butter",
    "2 cups vanilla wafers  (ground) into crumbs",
    "1 1/2 teaspoons vanilla",
    "3 cups powdered sugar",
    "1 egg",
    "2 c Fresh strawberry puree",
    "1 tbsp Lemon juice",
    "1 c Applesauce",
    "1/4 c Sugar",
    "1/2 cup water",
    "1/2 cup white vinegar",
    "1/2 cup white sugar",
    "1/2 cup soy sauce",
    "1 Tbsp apple cider vinegar",
    "1/2 tsp sesame seed oil",
    "1/4 tsp garlic powder",
    "1/4 tsp onion powder",
    "1/4 tsp powdered ginger",
    "Heaped 1/4 tsp of marmite",
    "1/4 tsp of corn syrup",
    "1/4 tbsp of ground black pepper",
    "4 eggs, beaten",
    "1 1/2 C grated Cheese",
    "1 small onion, peeled and chopped",
    "6 rashers bacon, chopped",
    "1 1/2 C self-raising Flour",
    "1 1/2 C milk",
    "1/4 C chopped parsley",
    "salt and pepper",
    "2 C of mushrooms, peppers, corn, peas, beans, pumpkin",
    "2 Kg Tomatoes",
    "600g Apple",
    "3 big Onions",
    "510 g Sugar",
    "55 g Salt",
    "1 1/4 C Vinegar",
    "10 g Cloves",
    "1/2 tsp Black Peppercorns",
    "1/2 tsp allspice",
    "5 g (1 tsp) active yeast",
    "approximately 180 ml lukewarm water",
    "300 g (2 C) strong flour",
    "1 1/2 tbsp milk powder",
    "1 tsp salt",
    "1 tsp sugar",
    "15 g butter, cold but pliable",
    "egg wash",
    "sesame seeds or poppy seeds",
    "3 C Flour",
    "5 tsp Baking Powder",
    "2 Tbsp mixed herbs",
    "1 tsp Salt",
    "330 ml Beer",
]

testIngredients = [
    '1 cup (2-3) mashed bananas', '5 g (1 tsp) active yeast', '300 g (2 C) strong flour'
]

testIngredients = allIngredients

